# 测试环境配置

server:
  port: 8687


spring:
  servlet:
   multipart:
     max-file-size: 10
  profiles: test
  datasource1:
    url: jdbc:mysql://10.0.53.179:3306/crt_wanjia?characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username:
    password:
    hikari:
      maxLifetime: 1765000
      maximumPoolSize: 20
      connectionTimeout: 30000
      idleTimeout: 600000

